import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 */
const sidebars: SidebarsConfig = {
  // Multi-Agent Systems Chapter Sidebar
  multiAgentSidebar: [
    {
      type: 'category',
      label: 'Multi-Agent AI Systems',
      collapsible: false,
      className: 'chapter-header',
      items: [
        {
          type: 'doc',
          id: 'multi-agent-systems/introduction',
          label: '1. Introduction',
        },
        {
          type: 'doc',
          id: 'multi-agent-systems/architectures',
          label: '2. Architectures',
        },
        {
          type: 'doc',
          id: 'multi-agent-systems/example',
          label: '3. Working Example',
        },
        {
          type: 'doc',
          id: 'multi-agent-systems/best-practices',
          label: '4. Best Practices',
        },
        {
          type: 'doc',
          id: 'multi-agent-systems/exercises',
          label: '5. Exercises',
        },
        {
          type: 'doc',
          id: 'multi-agent-systems/summary',
          label: '6. Summary',
        },
      ],
    },
  ],

  // Tutorial sidebar (auto-generated from tutorial directory)
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],

  // Default sidebar using autogenerated from docs
  docs: [
    {
      type: 'category',
      label: 'Multi-Agent AI Systems',
      items: [
        {
          type: 'doc',
          id: 'multi-agent-systems/introduction',
          label: 'Introduction',
        },
        {
          type: 'doc',
          id: 'multi-agent-systems/architectures',
          label: 'Architectures',
        },
        {
          type: 'doc',
          id: 'multi-agent-systems/example',
          label: 'Working Example',
        },
        {
          type: 'doc',
          id: 'multi-agent-systems/best-practices',
          label: 'Best Practices',
        },
        {
          type: 'doc',
          id: 'multi-agent-systems/exercises',
          label: 'Exercises',
        },
        {
          type: 'doc',
          id: 'multi-agent-systems/summary',
          label: 'Summary',
        },
      ],
    },
  ],
};

export default sidebars;
